#!/bin/sh

# System Shutdown Script
#

echo
echo "System is going down for reboot or halt now."
echo


echo "Starting stop scripts."

for i in /etc/rc0.d/stop/*
do
	if [ -x $i ]; then
		$i stop
	fi
done

