#!/bin/sh

# System Startup Script
# 

export PATH=$PATH:/etc/init.d

echo "Runnig startup script"

umask 022

  for i in /etc/rcS.d/S??*
  do
     [ ! -f  "$i" ] && continue;
     $i start       
  done

/bin/sh
